# # atlantis-service.yaml
# apiVersion: v1
# kind: Service
# metadata:
#   name: atlantis
#   namespace: atlantis
#   annotations:
#     service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
# spec:
#   type: LoadBalancer
#   selector:
#     app.kubernetes.io/name: atlantis
#   ports:
#     - name: http
#       port: 80
#       targetPort: 4141
