

gateway:
  type: LoadBalancer
  externalTrafficPolicy: Local
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"

  http:
    enabled: true
    servicePort: 80
    containerPort: 9080

  tls:
    enabled: true
    servicePort: 443
    containerPort: 9443

apisix:
  replicaCount: 2
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"

ingressController:
  enabled: true
